name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run end to end test
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Compile action
        run: npm run dist
      - name: Run local dot-npmrc action
        uses: ./
        with:
          root: '.'
          org: 'example-org'
          registry: 'npm.pkg.github.com'
          token: 'example-token'
      - name: Check if the result is correct
        uses: tianhaoz95-actions/file-diff@v1.1.0
        with:
          lhs: '.npmrc'
          rhs: '.npmrc.example'
          compare: 'true'

